sudo: required
services:
  - docker

before_install:
  - docker build -t socialcore/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true socialcore/docker-react-test npm run test -- --coverage
  
